---
# 4. KNN_iris
---

In [ ]:
from sklearn.datasets import load_iris 
iris = load_iris() 

X = iris.data[:, :4] 
y = iris.target 

In [2]:
X, y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [3]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 

In [5]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler() 

scaler.fit(X_train) 

X_train = scaler.transform(X_train) 
X_test = scaler.transform(X_test) 

In [6]:
X_train, X_test

(array([[-0.18975715,  3.21136841, -1.35133244, -1.10422988],
        [-0.07177343, -1.00026229,  0.09963296, -0.02911762],
        [-0.07177343, -0.53230333,  0.73805773,  1.58355077],
        [ 0.99008005,  0.63759409,  1.08628943,  1.18038367],
        [-1.25161063,  0.87157358, -1.29329382, -1.37300795],
        [ 0.51814517, -1.70220074,  0.33178742,  0.10527141],
        [-0.89765947,  0.63759409, -1.23525521, -0.96984085],
        [-1.13362691, -0.06434436, -1.40937106, -1.37300795],
        [ 1.22604749,  0.16963513,  0.73805773,  1.44916173],
        [-0.89765947,  1.80749151, -1.11917798, -1.10422988],
        [ 0.16419401,  0.87157358,  0.38982604,  0.50843851],
        [-1.48757807,  0.87157358, -1.40937106, -1.23861892],
        [ 0.99008005, -1.23424178,  1.14432804,  0.77721657],
        [-1.36959435,  0.40361461, -1.46740967, -1.37300795],
        [ 0.51814517,  0.87157358,  1.02825081,  1.58355077],
        [ 0.75411261, -0.06434436,  0.79609635,  1.04599464],
        

In [15]:
y_train, y_test

(array([0, 1, 2, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 0, 2, 2, 2, 2, 0, 2, 1, 0,
        1, 0, 0, 0, 0, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 0, 0, 1, 2, 0, 0,
        0, 2, 0, 1, 1, 0, 0, 1, 2, 2, 2, 0, 1, 1, 2, 1, 0, 0, 1, 1, 1, 2,
        0, 1, 2, 1, 2, 1, 1, 0, 2, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 2, 2,
        1, 2, 2, 1, 0, 2, 0, 0, 2, 1, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2,
        1, 1, 2, 0, 1, 1, 2, 0, 1, 1]),
 array([0, 1, 2, 2, 0, 0, 1, 0, 1, 0, 2, 2, 0, 2, 2, 1, 2, 1, 2, 0, 0, 2,
        0, 0, 2, 0, 0, 0, 1, 2]))

In [7]:
import numpy as np 
from sklearn.neighbors import KNeighborsRegressor

In [8]:
knnr = KNeighborsRegressor(n_neighbors=8) 
knnr.fit(X_train, y_train) 

KNeighborsRegressor(n_neighbors=8)

In [13]:
knnr.predict(X)

array([1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875,
       1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875,
       1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875,
       1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875,
       1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875, 1.875,
       1.875, 1.875, 1.875, 1.875, 1.875, 2.   , 2.   , 2.   , 2.   ,
       2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   ,
       2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   ,
       2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   ,
       2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   ,
       2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   ,
       2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   ,
       2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   ,
       2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   , 2.   ,
       2.   , 2.   ,

In [14]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
y-knnr.predict(X) #실제값 - 예측값

array([-1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875,
       -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875,
       -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875,
       -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875,
       -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875,
       -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875, -1.875,
       -1.875, -1.875, -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
       -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
       -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
       -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
       -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
       -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   , -1.   ,
       -1.   , -1.   , -1.   , -1.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
      

In [9]:
print ("The MSE is:",format(np.power(y-knnr.predict(X),4).mean())) 

The MSE is: 4.453206380208333


In [10]:
import numpy as np 

x1 = range(6) 
x1

range(0, 6)

In [11]:
print(np.power(x1,3)) 

[  0   1   8  27  64 125]


In [16]:
X = [[0], [1], [2], [3]] 
y = [0, 0, 1, 1] 

from sklearn.neighbors import KNeighborsRegressor 
knnr = KNeighborsRegressor(n_neighbors=3) 
knnr.fit(X, y) 
print(knnr.predict([[2.5]]))

[0.66666667]
