---
# 085. KNN_like
---
## 5.1. 데이터 불러오기

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
like=pd.read_csv('../data/like.csv')

말이 많은 정도  책을 좋아하는 정도  여행을 좋아하는 정도  학교성적   키  피부가 좋은 정도  근육질의 정도 호감LABEL
0        30          80           40    40  90         90       50     1타입
1        60          50           70    50  60         60       90     2타입
2        50          40           80    60  50         70       80     2타입
3        90          50           60    30  40         20       30     3타입
4        50          70           30    70  70         80       60     1타입

## 5.2. 데이터 전처리

In [9]:
like.columns=['talk','book','travel','school','tall','skin','musle','like_level']
like.head()

talk  book  travel  school  tall  skin  musle like_level
0    30    80      40      40    90    90     50        1타입
1    60    50      70      50    60    60     90        2타입
2    50    40      80      60    50    70     80        2타입
3    90    50      60      30    40    20     30        3타입
4    50    70      30      70    70    80     60        1타입

In [10]:
like.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   talk        14 non-null     int64 
 1   book        14 non-null     int64 
 2   travel      14 non-null     int64 
 3   school      14 non-null     int64 
 4   tall        14 non-null     int64 
 5   skin        14 non-null     int64 
 6   musle       14 non-null     int64 
 7   like_level  14 non-null     object
dtypes: int64(7), object(1)
memory usage: 1.0+ KB


## 5.3. 입력과  타겟 데이터를 분리

In [11]:
x=np.array(like.drop('like_level', axis=1))
print(x.shape)

(14, 7)


In [12]:
y=np.array(like.like_level)
print(y.shape)

(14,)


In [13]:
print(x)
print()
print(y)

[[30 80 40 40 90 90 50]
 [60 50 70 50 60 60 90]
 [50 40 80 60 50 70 80]
 [90 50 60 30 40 20 30]
 [50 70 30 70 70 80 60]
 [70 30 60 40 40 40 30]
 [40 90 60 60 60 80 60]
 [30 60 90 60 40 70 70]
 [80 40 20 80 60 40 50]
 [50 70 70 50 70 90 50]
 [80 50 60 40 50 40 70]
 [30 70 30 90 70 80 60]
 [40 60 90 60 50 70 80]
 [80 30 50 50 80 40 60]]

['1타입' '2타입' '2타입' '3타입' '1타입' '3타입' '1타입' '2타입' '3타입' '1타입' '3타입' '1타입'
 '2타입' '3타입']


## 5.4. 데이터 정규화 후 data 훈련

In [15]:
## 데이터 정규화 >> StandardScaler
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(x) #data 훈련

x=scaler.transform(x)
x

array([[-1.26962211e+00,  1.34164079e+00, -8.46121804e-01,
        -9.87829161e-01,  2.06644812e+00,  1.29927838e+00,
        -5.91607978e-01],
       [ 2.11603685e-01, -3.65902033e-01,  5.75362827e-01,
        -3.59210604e-01,  4.80569331e-02, -9.99444907e-02,
         1.77482393e+00],
       [-2.82138246e-01, -9.35082972e-01,  1.04919104e+00,
         2.69407953e-01, -6.24740131e-01,  3.66463133e-01,
         1.18321596e+00],
       [ 1.69282948e+00, -3.65902033e-01,  1.01534617e-01,
        -1.61644772e+00, -1.29753719e+00, -1.96557498e+00,
        -1.77482393e+00],
       [-2.82138246e-01,  7.72459847e-01, -1.31995001e+00,
         8.98026510e-01,  7.20853997e-01,  8.32870756e-01,
        -1.58603289e-17],
       [ 7.05345616e-01, -1.50426391e+00,  1.01534617e-01,
        -9.87829161e-01, -1.29753719e+00, -1.03275974e+00,
        -1.77482393e+00],
       [-7.75880177e-01,  1.91082173e+00,  1.01534617e-01,
         2.69407953e-01,  4.80569331e-02,  8.32870756e-01,
        -1.5860328

## 5.5. knn 분류 모델 생성 (범주형 데이터 분석)

In [16]:
from sklearn.neighbors import KNeighborsClassifier

classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x,y)

KNeighborsClassifier()

In [17]:
# 원래의 데이터를 넣어서 예측
y_pred=classifier.predict(x)
y_pred

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [18]:
y

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

## 5.6. 모델 평가

In [19]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y, y_pred))#실제 값과 여측값 비교
print(classification_report(y, y_pred))

[[5 0 0]
 [0 4 0]
 [0 0 5]]
              precision    recall  f1-score   support

         1타입       1.00      1.00      1.00         5
         2타입       1.00      1.00      1.00         4
         3타입       1.00      1.00      1.00         5

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14

