In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

from sklearn import tree, ensemble
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn import datasets

diabetes = datasets.load_diabetes()

In [2]:
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [3]:
x=diabetes.data
y=diabetes.target
feature=diabetes.feature_names

In [4]:
x, x.shape, feature

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 (442, 10),
 ['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'])

In [5]:
y, y.shape

(array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128., 

In [6]:
#정규화=>안하면 성능이 떨어짐, 단위가 다르기 때문이다.
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x)

StandardScaler()

In [7]:
x_regu=scaler.transform(x)

In [8]:
x_regu, x_regu.shape

(array([[ 0.80050009,  1.06548848,  1.29708846, ..., -0.05449919,
          0.41855058, -0.37098854],
        [-0.03956713, -0.93853666, -1.08218016, ..., -0.83030083,
         -1.43655059, -1.93847913],
        [ 1.79330681,  1.06548848,  0.93453324, ..., -0.05449919,
          0.06020733, -0.54515416],
        ...,
        [ 0.87686984,  1.06548848, -0.33441002, ..., -0.23293356,
         -0.98558469,  0.32567395],
        [-0.9560041 , -0.93853666,  0.82123474, ...,  0.55838411,
          0.93615545, -0.54515416],
        [-0.9560041 , -0.93853666, -1.53537419, ..., -0.83030083,
         -0.08871747,  0.06442552]]),
 (442, 10))

In [9]:
#랜덤 회귀모델
model=ensemble.RandomForestRegressor()

In [10]:
#정규화 하지 않은 모델 model_1
model_1=model.fit(x, y)
model_1

In [15]:
#정규화 한 모델 model_2 #여긴이미 정규화 되있으나 요령
model_2=model.fit(x_regu, y)
model_2

RandomForestRegressor()

In [11]:
#결정계수
r2=model_1.score(x,y)
r2
#92%의 설명력

0.9199658232989676

In [16]:
#정규화 한 결정계수
r2=model_2.score(x_regu,y)
r2
#92%의 설명력

0.9179315857794205

In [13]:
#예측
model_1.predict(x)

array([175.92,  84.54, 157.01, 192.93, 118.02, 103.45, 113.78,  94.65,
       125.66, 256.73, 106.73,  94.45, 150.02, 182.68, 113.84, 182.49,
       182.39, 161.12, 108.27, 134.17,  93.28,  66.1 ,  77.71, 243.26,
       169.  , 181.9 , 120.39, 110.99, 136.16, 250.79, 133.93,  63.4 ,
       286.72,  96.39,  66.06, 122.49, 247.64, 223.52, 247.08, 118.23,
       137.14,  87.89,  80.56,  91.2 , 239.48,  65.27, 164.43, 134.57,
        79.05, 162.2 , 139.55, 208.67,  80.28, 106.04, 162.77, 108.83,
       115.04,  53.09, 147.41, 160.43,  80.98, 141.35,  58.73, 129.85,
        94.51, 170.15, 138.96,  99.49, 132.1 , 140.88,  61.87, 260.15,
       189.78, 110.26, 110.84,  69.56, 172.47, 156.92, 209.52, 120.35,
       155.41,  78.69,  69.24, 194.42,  74.09, 147.16,  63.71, 146.78,
        61.52, 101.62,  90.91, 160.33,  83.39,  86.97,  95.98, 146.39,
       172.75, 242.49,  97.28, 108.76, 162.43,  99.81, 249.79, 182.33,
       108.41,  77.71, 124.44, 135.87, 236.32, 105.86,  97.69,  68.86,
      